package com.buildledger.notification.enums;
public enum NotificationType { VENDOR_APPROVED, VENDOR_REJECTED, CONTRACT_ACTIVATED, INVOICE_APPROVED, INVOICE_REJECTED, PAYMENT_COMPLETED, DELIVERY_ACCEPTED, DELIVERY_REJECTED, AUDIT_SCHEDULED, COMPLIANCE_FAILED, GENERAL }

